version: "3"

services:
  backend:
    container_name: backend
    build: backend/
    ports:
      - "8000:8000"
    networks:
      - deploy_network

  interface:
    container_name: frontend
    build: frontend/
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge
